### PR TITLE
Replace Nokogiri parser with Oga parser

### PR DESCRIPTION
**Pull request by syntaxTerr0r**
#28 - Replace Nokogiri with Oga for HTML parsing.

### CODE REVIEW

**Comment by syntaxTerr0r** [comment]
CI problem on jruby & rbx, seems like it's a travis configuration issue. Oga supports both jruby & rbx.

**Comment by michaelbaudino** [comment]
Hi @syntaxTerr0r, I love that idea :heart_eyes:

I just need to find some time to test this PR out before merging it (and port it to the `v3` branch), which will unfortunately not be in the next few days. But I want you to know that your work is not left unread nor forgotten and is actually greatly appreciated :+1: 

I'll give it a look as soon as I can, thank a lot for this contribution :tophat:

**Comment by syntaxTerr0r** [comment]
Up? 😅

**Comment by michaelbaudino** [comment]
OK, I finally had a look at your PR @syntaxTerr0r... it's never too late, right? :sweat_smile: 

It looks good to me, and I love the idea of not depending on an external `libxml2` library :+1: 

It's a lot slower, though... it takes approximatively 80% more time, according to this not-scientific-at-all tests:
```shell
→ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
→ time bundle exec bin/addic7ed Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION\[eztv\].mkv 
New subtitle downloaded for Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION[eztv].mkv.
Enjoy your show :-)

real	0m10.655s
user	0m0.531s
sys	0m0.019s
→ rm Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION\[eztv\].fr.srt 
→ time bundle exec bin/addic7ed Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION\[eztv\].mkv 
New subtitle downloaded for Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION[eztv].mkv.
Enjoy your show :-)

real	0m9.198s
user	0m0.512s
sys	0m0.039s
→ rm Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION\[eztv\].fr.srt 
→ time bundle exec bin/addic7ed Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION\[eztv\].mkv 
New subtitle downloaded for Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION[eztv].mkv.
Enjoy your show :-)

real	0m9.249s
user	0m0.523s
sys	0m0.031s
→ rm Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION\[eztv\].fr.srt 
→ 
→ 
→ 
→ git checkout syntaxTerr0r-master
Switched to branch 'syntaxTerr0r-master'
→ time bundle exec bin/addic7ed Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION\[eztv\].mkv 
New subtitle downloaded for Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION[eztv].mkv.
Enjoy your show :-)

real	0m18.264s
user	0m9.654s
sys	0m0.055s
→ rm Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION\[eztv\].fr.srt 
→ time bundle exec bin/addic7ed Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION\[eztv\].mkv 
New subtitle downloaded for Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION[eztv].mkv.
Enjoy your show :-)

real	0m18.976s
user	0m9.367s
sys	0m0.063s
→ rm Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION\[eztv\].fr.srt 
→ time bundle exec bin/addic7ed Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION\[eztv\].mkv 
New subtitle downloaded for Greys.Anatomy.S13E10.720p.HDTV.X264-DIMENSION[eztv].mkv.
Enjoy your show :-)

real	0m18.466s
user	0m9.687s
sys	0m0.055s
```

But I believe it's an acceptable tradeoff :+1:

**Comment by michaelbaudino** [comment]
I just published it, but as a major bump (since it may be considered breaking change due to the dependencies change). So it's now `3.0.0` :champagne: 

Thanks a lot for your contribution :love_letter:

**Comment by michaelbaudino** [comment]
Did I mention the performance issue we saw in this issue was due to the use of the super-slow `:not(:first-child)` CSS selector and that it has been fixed in 350805fb2c2949b89795771fbec00a331b1c2603 ? 😏

**Pull request merged**
