### PR TITLE
Add optional distribution group name in the filename

### PR DESCRIPTION
**Pull request by harg**
Add support for an optional distribution group name in the video filename

Example : 
The.Walking.Dead.S03E02.720p.HDTV.x264-EVOLVE[ettv].mkv

It does not modify the downloading logic.

### CODE REVIEW

**Comment by michaelbaudino** [comment]
This looks like a great idea :sparkles: 

The specs should not have a distribution group in every test, though: we should have a test that checks that it works with a distribution group, and leave all other tests as they were.
Can you change this and rebase (it does not merge anymore).

Thanks for this PR, anyway :+1:

**Comment by harg** [comment]
Here you go :smile:

**Comment by harg** [comment]
@michaelbaudino is it ok?

**Comment by michaelbaudino** [comment]
Ho yes, it looks great :sparkles: 

Could you merge `master` in this branch, though ? I'm seeing weirdnesses in the diff (stuff related to hearing-impaired subtitles). Maybe it'll fix Travis and Hakiri too ¯\\\_(ツ)\_/¯

Also, I did not know about Rspec `satisfy` matcher, thanks for that :+1:

**Comment by michaelbaudino** [comment]
Hrm, this is embarassing, but Travis fails on `master` actually. So please merge it to have a clean diff, but don't expect Travis to pass :disappointed: 
I'll have a look at that Travis error tomorrow morning.

**Comment by harg** [comment]
Done! :+1:

**Comment by michaelbaudino** [comment]
Awesome, thanks :sparkles:

**Pull request merged**
